on:
  push:
    paths:
      - docs/anomaly_pdf/**/*.pdf
      - docs/gosi_pdf/**/*.pdf


jobs:
  convert-pdf-to-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install poppler-utils
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils
  
    - name: Install dependencies
      run: |
        npm install pdfjs-dist
  
    - name: Convert PDFs to HTML
      run: |
        mkdir -p html_output
        for pdf in anomaly_pdf/*.pdf; do
        filename=$(basename "$pdf" .pdf)
        pdf2htmlEX --dest-dir html_output "$pdf"
        done

    - name: Commit and push HTML files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add html_output
        git commit -m "Convert PDF to HTML for $(date +'%Y-%m-%d')"
        git push
